### ISSUE TITLE
README.md references an embed.html page that no longer exists

### ISSUE THREAD

**Issue by wasuaje** [fightforthefuture/battleforthenet#74]
https://www.battleforthenet.com/embed.html

That's not working for embed code in my site

![image](https://user-images.githubusercontent.com/4673741/28032822-5704141a-6582-11e7-8d49-dd014b621bd0.png)

**Comment by holmesworcester** [comment]
Perhaps you came to this from an old link?

This is the code: http://widget.battleforthenet.com/ <http://widget.battleforthenet.com/>

Can you tell me where you saw the other link? 

Holmes Wilson
fightforthefuture.org
+1 614-465-6371

**Comment by wasuaje** [comment]
Hello thanks for the answer

The old code is here in git hub source code!!!

**Comment by mikemorris** [comment]
`README.md` is out of date and references an embed page that was built for the 2014 Net Neutrality campaign. The 2017 widget can be found at https://github.com/fightforthefuture/battleforthenet-widget

Leaving this open because we need to update [`README.md`](https://github.com/fightforthefuture/battleforthenet/blob/gh-pages/README.md) here.

**Comment by holmesworcester** [comment]
updated.

**Comment by wasuaje** [comment]
Cool Thanks
